class ParticipantMatch < ApplicationRecord
  establish_connection "#{Rails.env}_omop".to_sym
  belongs_to :submission
  has_many :participant_match_details

  PARTICIPANT_MATCH_DETERMINATION_MATCH = 'match'
  PARTICIPANT_MATCH_DETERMINATION_NO_MATCH = 'no_match'
  PARTICIPANT_MATCH_DETERMINATION_MISSING = 'missing'
  PARTICIPANT_MATCH_DETERMINATION_EXCLUDED = 'excluded'
  PARTICIPANT_MATCH_DETERMINATIONS = [PARTICIPANT_MATCH_DETERMINATION_MATCH, PARTICIPANT_MATCH_DETERMINATION_NO_MATCH, PARTICIPANT_MATCH_DETERMINATION_MISSING, PARTICIPANT_MATCH_DETERMINATION_EXCLUDED]

  PARTICIPANT_MATCH_ALGORITHM_VALIDATION_YES = 'yes'
  PARTICIPANT_MATCH_ALGORITHM_VALIDATION_NO = 'no'
  PARTICIPANT_MATCH_ALGORITHM_VALIDATIONS = [PARTICIPANT_MATCH_ALGORITHM_VALIDATION_YES, PARTICIPANT_MATCH_ALGORITHM_VALIDATION_NO]

  PARTICIPANT_MATCH_MANUAL_VALIDATION_YES = 'yes'
  PARTICIPANT_MATCH_MANUAL_VALIDATION_NO = 'no'
  PARTICIPANT_MATCH_MANUAL_VALIDATION_UNDETERMINED = 'undetermined'
  PARTICIPANT_MATCH_MANUAL_VALIDATIONS = [PARTICIPANT_MATCH_MANUAL_VALIDATION_YES, PARTICIPANT_MATCH_MANUAL_VALIDATION_NO, PARTICIPANT_MATCH_MANUAL_VALIDATION_UNDETERMINED]
end